###
GET http://localhost:4004/odata/v4/trackservice/$metadata

###
POST http://localhost:4004/odata/v4/trackservice/BoxLineItem
Content-Type: application/json

{
    "productCode" : "P0004",
    "QrCode"      : "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=%7B%22productCode%22%3A%22P002%22%2C%22batchId%22%3A%22B002%22%2C%22manufacturingDate%22%3A%222024-03-01%22%2C%22expiryDate%22%3A%222025-03-01%22%2C%22qrCode%22%3A%22%22%2C%22productionId%22%3A%22PR004%22%7D",
    "BatchId"     : "BT3",
    "CreationDate":"2024-08-01"
}


###

POST http://localhost:4004/odata/v4/trackservice/InnerContainer
Content-Type: application/json

{
  "innerContainerId": "IC001",
  "qrCode": "QRCode_IC001",
  "creationDate": "2024-12-30T10:00:00Z",
  "PerfumeBottles": [
    {
      "productCode": "P001",
      "batchId": "B001",
      "manufacturedDate": "2024-12-20",
      "qrCode": "QRCode_P001"
    },
    {
      "productCode": "P002",
      "batchId": "B001",
      "manufacturedDate": "2024-12-21",
      "qrCode": "QRCode_P002"
    }
  ]
}



###
GET http://localhost:4004/odata/v4/trackservice/MaterialBox?BatchID='1000000080'


####
GET http://localhost:4004/odata/v4/trackservice/InnerContainer?BatchID='1000000080'



###

GET http://localhost:4004/odata/v4/trackservice/getBatchIDRelevantData?ManufactureDt=2025-01-06



###
GET http://localhost:4004/odata/v4/trackservice/getBatchOCValueHelp?BatchID='1000000080'


####
GET http://localhost:4004/odata/v4/trackservice/getBatchIDRelevantData?BatchNo='1000000080'&filterNonEmptyBoxQRCode=true

####


GET http://localhost:4004/odata/v4/trackservice/getBatchIDRelevantData?ProductionOrder='1000270'&filterNonEmptyBoxQRCode=true


###
POST http://localhost:4004/odata/v4/trackservice/MaterialBox
Content-Type: application/json

{
  "SerialNo": "10011194",
  "BatchID": "1000000077"
}

#####
POST http://localhost:4004/odata/v4/trackservice/OuterContainer
Content-Type: application/json

 {
  "BatchID": "1000000080",
  "ICs": [
    { "ICID": "06012027" },
    { "ICID": "06012026" }
  ],
  "status": "Inventory"
}


###

POST http://localhost:4004/odata/v4/trackservice/InnerContainer
Content-Type: application/json

{
  "BatchID": "1000000080",
  "Boxes": [
   {
      "SerialNo": "10011218",
      "BoxQRCode": "00004fv09k"
    },
    {
      "SerialNo": "10011222",
      "BoxQRCode": "00004fv09u"
    }
    
  ]
}


####

GET http://localhost:4004/odata/v4/trackservice/OuterContainer

###

GET http://localhost:4004/odata/v4/trackservice/getBatchOcDealerMappingdata?BatchID='1000000080'& OCID='00000001'

###

PATCH http://localhost:4004/odata/v4/trackservice/OuterContainer(OCID='00000001', OCQRCode='00001nz57r', OCQRCodeURL='https://api.qrserver.com/v1/create-qr-code/?size=600x600&data=%7B%22OCID%22%3A%2200000001%22%2C%22BatchID%22%3A%221000000080%22%2C%22status%22%3A%22Inventory%22%2C%22ManufactureDt%22%3A%222025-01-06%22%2C%22ExpiryDt%22%3A%222026-01-06%22%2C%22ProductionOrder%22%3A%221000270%22%2C%22Material%22%3A%222000000163%22%2C%22ICs%22%3A%5B%7B%22ICID%22%3A%2206012027%22%2C%22Boxes%22%3A%5B%7B%22SerialNo%22%3A%2210011218%22%7D%2C%7B%22SerialNo%22%3A%2210011219%22%7D%5D%7D%2C%7B%22ICID%22%3A%2206012026%22%2C%22Boxes%22%3A%5B%7B%22SerialNo%22%3A%2210011216%22%7D%2C%7B%22SerialNo%22%3A%2210011217%22%7D%5D%7D%5D%7D')
Content-Type: application/json

{
  "VendorId": "21000000",
  "VendorName": "Blues Perfume",
  "status": "Dealer Assigned"
}


###
PATCH http://localhost:4004/odata/v4/trackservice/OuterContainer(OCID='00000001',OCQRCodeURL='',OCQRCode='')
Content-Type: application/json

{
  "VendorId": "21000000",
  "VendorName": "Blues Perfume",
  "status": "Dealer Assigned"
}



###

GET http://localhost:4004/odata/v4/trackservice/getProductionTrackingDashboardData?OCID='00000001'


###

GET http://localhost:4004/odata/v4/trackservice/getDealerDashOCValueHelp?VendorId='21000000'











###
