###
GET http://localhost:4004/odata/v4/trackservice/$metadata

###
POST http://localhost:4004/odata/v4/trackservice/BoxLineItem
Content-Type: application/json

{
    "productCode" : "P0004",
    "QrCode"      : "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=%7B%22productCode%22%3A%22P002%22%2C%22batchId%22%3A%22B002%22%2C%22manufacturingDate%22%3A%222024-03-01%22%2C%22expiryDate%22%3A%222025-03-01%22%2C%22qrCode%22%3A%22%22%2C%22productionId%22%3A%22PR004%22%7D",
    "BatchId"     : "BT3",
    "CreationDate":"2024-08-01"
}


###

POST http://localhost:4004/odata/v4/trackservice/InnerContainer
Content-Type: application/json

{
  "innerContainerId": "IC001",
  "qrCode": "QRCode_IC001",
  "creationDate": "2024-12-30T10:00:00Z",
  "PerfumeBottles": [
    {
      "productCode": "P001",
      "batchId": "B001",
      "manufacturedDate": "2024-12-20",
      "qrCode": "QRCode_P001"
    },
    {
      "productCode": "P002",
      "batchId": "B001",
      "manufacturedDate": "2024-12-21",
      "qrCode": "QRCode_P002"
    }
  ]
}



###
GET http://localhost:4004/odata/v4/trackservice/MaterialBox?BatchID='1000000080'


####
GET http://localhost:4004/odata/v4/trackservice/InnerContainer?BatchID='1000000080'



###

GET http://localhost:4004/odata/v4/trackservice/getBatchIDRelevantData?BatchNo='1000000080'

####
GET http://localhost:4004/odata/v4/trackservice/getBatchIDRelevantData?BatchNo='1000000080'&filterNonEmptyBoxQRCode=true


###
POST http://localhost:4004/odata/v4/trackservice/MaterialBox
Content-Type: application/json

{
  "SerialNo": "10011194",
  "BatchID": "1000000077"
}

#####
POST http://localhost:4004/odata/v4/trackservice/OuterContainer
Content-Type: application/json

 {
    "BatchID": "1000000080",
    "ICs": [
        { "ICID": "06012026" },
        { "ICID": "06012027" }
    ]
}


###

POST http://localhost:4004/odata/v4/trackservice/InnerContainer
Content-Type: application/json

{
  "BatchID": "1000000080",
  "Boxes": [
   {
      "SerialNo": "10011218",
      "BoxQRCode": "00004fv09k"
    },
    {
      "SerialNo": "10011222",
      "BoxQRCode": "00004fv09u"
    }
    
  ]
}


####

GET http://localhost:4004/odata/v4/trackservice/OuterContainer








###
POST http://localhost:4004/odata/v4/trackservice/PerfumeBottles
Content-Type: application/json

{
      "productCode": "P001",
      "batchId": "B001",
      "manufacturedDate": "2024-12-20",
      "qrCode": "QRCode_P001",
      "innerContainerId_innerContainerId": ""
}
